# Generated by Django 4.1 on 2023-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('year', models.DateField()),
                ('engine', models.FloatField()),
                ('color', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
    ]
