# Generated by Django 4.1 on 2023-04-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carcheck', '0003_remove_carowner_car_car_owner_alter_carimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/cefzim_l6hc-o2.jpg', upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carcheck.carowner'),
        ),
    ]
